class ExpectedValues:
    def __init__(self):

        self.toc_expected = [
            [1, "By Form", 1],
            [2, "Adverse Events", 22],
            [3, "Running Records", 22],
            [2, "Auditory Verbal Learning Test (AVLT-REY)", 17],
            [3, "Screening 2", 17],
            [3, "Week 4", 17],
            [3, "Week 8", 17],
            [3, "Week 12", 17],
            [3, "Week 16", 17],
            [3, "Week 20", 17],
            [3, "Week 24", 17],
            [3, "Early Discontinuation Retrieval", 17],
            [2, "Concomitant Medications", 25],
            [3, "Running Records", 25],
            [2, "Death Details", 26],
            [3, "Running Records", 26],
            [2, "Demographics", 5],
            [3, "Screening 1", 5],
            [2, "Electroencephalogram", 20],
            [3, "Running Records", 20],
            [2, "Eligibility", 6],
            [3, "Screening 1", 6],
            [2, "End Of Treatment", 27],
            [3, "Week 26", 27],
            [2, "Exposure", 14],
            [3, "Running Records", 14],
            [2, "Hamilton Depression Rating Scale - 17 (HAMD-17)", 19],
            [3, "Baseline", 19],
            [3, "Early Discontinuation Retrieval", 19],
            [2, "Informed Consent", 5],
            [3, "Screening 1", 5],
            [2, "Injection Site Reactions", 23],
            [3, "Running Records", 23],
            [2, "Medical History", 7],
            [3, "Screening 1", 7],
            [2, "Ophthalmic Examination", 21],
            [3, "Screening 1", 21],
            [3, "Screening 2", 21],
            [3, "Baseline", 21],
            [3, "Week 2", 21],
            [3, "Week 4", 21],
            [3, "Week 8", 21],
            [3, "Week 12", 21],
            [3, "Week 16", 21],
            [3, "Week 20", 21],
            [3, "Week 24", 21],
            [3, "Week 26", 21],
            [3, "Early Discontinuation Retrieval", 21],
            [2, "Patient Health Questionnaire-9 (PHQ-9)", 15],
            [3, "Baseline", 15],
            [3, "Week 12", 15],
            [3, "Week 16", 15],
            [3, "Week 20", 15],
            [3, "Week 24", 15],
            [3, "Early Discontinuation Retrieval", 15],
            [2, "Patient Summary", 28],
            [3, "Week 26", 28],
            [2, "Satisfaction With Life Survey (SWLS)", 16],
            [3, "Baseline", 16],
            [3, "Week 12", 16],
            [3, "Week 16", 16],
            [3, "Week 20", 16],
            [3, "Week 24", 16],
            [3, "Early Discontinuation Retrieval", 16],
            [2, "Vital Signs (Temperature)", 11],
            [3, "Screening 2", 11],
            [3, "Early Discontinuation Retrieval", 11],
            [2, "Vital Signs (Weight And Temperature)", 12],
            [3, "Baseline", 12],
            [3, "Week 2", 12],
            [3, "Week 4", 12],
            [3, "Week 6", 12],
            [3, "Week 8", 12],
            [3, "Week 12", 12],
            [3, "Week 16", 12],
            [3, "Week 20", 12],
            [3, "Week 24", 12],
            [3, "Week 26", 12],
            [2, "Vital Signs (Weight, Height And Temperature)", 8],
            [3, "Screening 1", 8],
            [1, "By Visit", 1],
            [2, "Running Records", 22],
            [3, "Adverse Events", 22],
            [3, "Concomitant Medications", 25],
            [3, "Death Details", 26],
            [3, "Electroencephalogram", 20],
            [3, "Exposure", 14],
            [3, "Injection Site Reactions", 23],
            [2, "Screening 1", 5],
            [3, "Demographics", 5],
            [3, "Eligibility", 6],
            [3, "Informed Consent", 5],
            [3, "Medical History", 7],
            [3, "Ophthalmic Examination", 21],
            [3, "Vital Signs (Weight, Height And Temperature)", 8],
            [2, "Screening 2", 17],
            [3, "Auditory Verbal Learning Test (AVLT-REY)", 17],
            [3, "Ophthalmic Examination", 21],
            [3, "Vital Signs (Temperature)", 11],
            [2, "Baseline", 19],
            [3, "Hamilton Depression Rating Scale - 17 (HAMD-17)", 19],
            [3, "Ophthalmic Examination", 21],
            [3, "Patient Health Questionnaire-9 (PHQ-9)", 15],
            [3, "Satisfaction With Life Survey (SWLS)", 16],
            [3, "Vital Signs (Weight And Temperature)", 12],
            [2, "Week 2", 21],
            [3, "Ophthalmic Examination", 21],
            [3, "Vital Signs (Weight And Temperature)", 12],
            [2, "Week 4", 17],
            [3, "Auditory Verbal Learning Test (AVLT-REY)", 17],
            [3, "Ophthalmic Examination", 21],
            [3, "Vital Signs (Weight And Temperature)", 12],
            [2, "Week 6", 12],
            [3, "Vital Signs (Weight And Temperature)", 12],
            [2, "Week 8", 17],
            [3, "Auditory Verbal Learning Test (AVLT-REY)", 17],
            [3, "Ophthalmic Examination", 21],
            [3, "Vital Signs (Weight And Temperature)", 12],
            [2, "Week 12", 17],
            [3, "Auditory Verbal Learning Test (AVLT-REY)", 17],
            [3, "Ophthalmic Examination", 21],
            [3, "Patient Health Questionnaire-9 (PHQ-9)", 15],
            [3, "Satisfaction With Life Survey (SWLS)", 16],
            [3, "Vital Signs (Weight And Temperature)", 12],
            [2, "Week 16", 17],
            [3, "Auditory Verbal Learning Test (AVLT-REY)", 17],
            [3, "Ophthalmic Examination", 21],
            [3, "Patient Health Questionnaire-9 (PHQ-9)", 15],
            [3, "Satisfaction With Life Survey (SWLS)", 16],
            [3, "Vital Signs (Weight And Temperature)", 12],
            [2, "Week 20", 17],
            [3, "Auditory Verbal Learning Test (AVLT-REY)", 17],
            [3, "Ophthalmic Examination", 21],
            [3, "Patient Health Questionnaire-9 (PHQ-9)", 15],
            [3, "Satisfaction With Life Survey (SWLS)", 16],
            [3, "Vital Signs (Weight And Temperature)", 12],
            [2, "Week 24", 17],
            [3, "Auditory Verbal Learning Test (AVLT-REY)", 17],
            [3, "Ophthalmic Examination", 21],
            [3, "Patient Health Questionnaire-9 (PHQ-9)", 15],
            [3, "Satisfaction With Life Survey (SWLS)", 16],
            [3, "Vital Signs (Weight And Temperature)", 12],
            [2, "Week 26", 27],
            [3, "End Of Treatment", 27],
            [3, "Ophthalmic Examination", 21],
            [3, "Patient Summary", 28],
            [3, "Vital Signs (Weight And Temperature)", 12],
            [2, "Early Discontinuation Retrieval", 17],
            [3, "Auditory Verbal Learning Test (AVLT-REY)", 17],
            [3, "Hamilton Depression Rating Scale - 17 (HAMD-17)", 19],
            [3, "Ophthalmic Examination", 21],
            [3, "Patient Health Questionnaire-9 (PHQ-9)", 15],
            [3, "Satisfaction With Life Survey (SWLS)", 16],
            [3, "Vital Signs (Temperature)", 11],
        ]
